name:                hs-pastebin
version:             0.1.0.0
github:              "github.com/crosstyan/hs-pastebin"
license:             WTFPL
author:              "crosstyan"
maintainer:          "crosstyan@outlook.com"
copyright:           "2022 Crosstyan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/crosstyan/hs-pastebin#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- http-types
- wai-extra
- random
- aeson
- mtl
- text
- data-default-class
- containers
- hedis
- bytestring
- uuid
- utf8-string
- time

library:
  source-dirs: src

executables:
  hs-pastebin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-pastebin

tests:
  hs-pastebin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-pastebin
